version: '3.5'

services:
  helloworld:
    image: registry.services.alin.be/helloworld-alin:v1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 20M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=80
        - traefik.frontend.rule=Host:helloworld.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr

networks:
  default:
    external:
      name: traefik-net
